server:
  port: 33702
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: dzp961207@163.com
    password: BFGUTRYNZDCTEQUY
    default-encoding: UTF-8
    fromMail:
      sender: dzp961207@163.com
config:
  uuid: ${random.uuid}